server:
  port: 7050

spring:
  application:
    name: HOTEL-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/myservice_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: postgres
    password: 6969
  jpa:
    hibernate:
      ddl-auto: update   # <- DB entries auto update
    show-sql: true       # <- SQL true
  eureka:
    instance:
      prefer-ip-address: true
    client:
      fetch-registery: true
      register-with-eureka: true
      service-url:
        defaultZone: http://localhost:8761/eureka

  
      